### ISSUE TITLE
Release multiview

### ISSUE THREAD

**Issue by mariuani** [backlogs/redmine_backlogs#1049]
Hi,

If I want to see my Release multiview, I get bug:

Started GET "/redmine/rb/releases_multiview/1" for x.x.x.x at 2014-04-07 10:56:47 +0200
Processing by RbReleasesMultiviewController#show as _/_
Parameters: {"release_multiview_id"=>"1"}
Current user: nick (id=2067)
DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in #Module:0x000000038db848 instead. (called from realtime at /usr/lib64/ruby/1.9.1/benchmark.rb:295)
DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in Kaminari::ActiveRecordModelExtension instead. (called from <top (required)> at /var/www/html/redmine/plugins/redmine_backlogs/app/models/rb_release_burnchart_day_cache.rb:3)
DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in Kaminari::ConfigurationMethods instead. (called from <top (required)> at /var/www/html/redmine/plugins/redmine_backlogs/app/models/rb_release_burnchart_day_cache.rb:3)
Rendered plugins/redmine_backlogs/app/views/rb_releases_multiview/show.html.erb within layouts/base (55.6ms)
Completed 500 Internal Server Error in 74.3ms

ActionView::Template::Error (undefined method `predict_value' for nil:NilClass):
36: <% unless @release_multiview.has_burnchart? >
37: <= render :partial => 'releases', :locals => { :releases => @release_multiview.releases } >
38: < else >
39: <= render :partial => 'releases_estimate', :locals => { :releases => @release_multiview.burnchart.releases_estimate } >
40: < end %>
41:
42:
plugins/redmine_backlogs/lib/linear_regression.rb:36:in`crossing_date'
plugins/redmine_backlogs/app/models/rb_stacked_data.rb:89:in `block in calculate_estimate_end_days'
plugins/redmine_backlogs/app/models/rb_stacked_data.rb:88:in`each'
plugins/redmine_backlogs/app/models/rb_stacked_data.rb:88:in `calculate_estimate_end_days'
plugins/redmine_backlogs/app/models/rb_stacked_data.rb:60:in`finalize'
plugins/redmine_backlogs/app/models/rb_release_multiview_burnchart.rb:28:in `initialize'
plugins/redmine_backlogs/app/models/rb_release_multiview.rb:26:in`new'
plugins/redmine_backlogs/app/models/rb_release_multiview.rb:26:in `burnchart'
plugins/redmine_backlogs/app/views/rb_releases_multiview/show.html.erb:39:in`_plugins_redmine_backlogs_app_views_rb_releases_multiview_show_html_erb___3489366922716009181_59101560'
actionpack (3.2.16) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.16) lib/active_support/notifications.rb:125:in`instrument'
actionpack (3.2.16) lib/action_view/template.rb:143:in `render'
actionpack (3.2.16) lib/action_view/renderer/template_renderer.rb:47:in`block (2 levels) in render_template'
actionpack (3.2.16) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.16) lib/active_support/notifications.rb:123:in`block in instrument'
activesupport (3.2.16) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.16) lib/active_support/notifications.rb:123:in`instrument'
actionpack (3.2.16) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.16) lib/action_view/renderer/template_renderer.rb:46:in`block in render_template'
actionpack (3.2.16) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
actionpack (3.2.16) lib/action_view/renderer/template_renderer.rb:45:in`render_template'
actionpack (3.2.16) lib/action_view/renderer/template_renderer.rb:18:in `render'
actionpack (3.2.16) lib/action_view/renderer/renderer.rb:36:in`render_template'
actionpack (3.2.16) lib/action_view/renderer/renderer.rb:17:in `render'
actionpack (3.2.16) lib/abstract_controller/rendering.rb:110:in`_render_template'
actionpack (3.2.16) lib/action_controller/metal/streaming.rb:225:in `_render_template'
actionpack (3.2.16) lib/abstract_controller/rendering.rb:103:in`render_to_body'
actionpack (3.2.16) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
actionpack (3.2.16) lib/action_controller/metal/compatibility.rb:50:in`render_to_body'
actionpack (3.2.16) lib/abstract_controller/rendering.rb:88:in `render'
actionpack (3.2.16) lib/action_controller/metal/rendering.rb:16:in`render'
actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.2.16) lib/active_support/core_ext/benchmark.rb:5:in`block in ms'
/usr/lib64/ruby/1.9.1/benchmark.rb:295:in `realtime'
activesupport (3.2.16) lib/active_support/core_ext/benchmark.rb:5:in`ms'
actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:83:in`cleanup_view_runtime'
activerecord (3.2.16) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:39:in`render'
plugins/redmine_backlogs/app/controllers/rb_releases_multiview_controller.rb:13:in `block (2 levels) in show'
actionpack (3.2.16) lib/action_controller/metal/mime_responds.rb:196:in`call'
actionpack (3.2.16) lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
plugins/redmine_backlogs/app/controllers/rb_releases_multiview_controller.rb:12:in`show'
actionpack (3.2.16) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.16) lib/abstract_controller/base.rb:167:in`process_action'
actionpack (3.2.16) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.16) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
activesupport (3.2.16) lib/active_support/callbacks.rb:502:in `_run__522285431919528457__process_action__2762035493279309155__callbacks'
activesupport (3.2.16) lib/active_support/callbacks.rb:405:in`__run_callback'
activesupport (3.2.16) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.16) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (3.2.16) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.16) lib/action_controller/metal/rescue.rb:29:in`process_action'
actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.16) lib/active_support/notifications.rb:123:in`block in instrument'
activesupport (3.2.16) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.16) lib/active_support/notifications.rb:123:in`instrument'
actionpack (3.2.16) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.16) lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
activerecord (3.2.16) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.2.16) lib/abstract_controller/base.rb:121:in`process'
actionpack (3.2.16) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.16) lib/action_controller/metal.rb:203:in`dispatch'
actionpack (3.2.16) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.16) lib/action_controller/metal.rb:246:in`block in action'
actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in`block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in`call'
actionpack (3.2.16) lib/action_dispatch/routing/route_set.rb:608:in `call'
rack-raw-upload (1.1.1) lib/rack/raw_upload.rb:18:in`call'
rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
actionpack (3.2.16) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
rack (1.4.5) lib/rack/etag.rb:23:in `call'
rack (1.4.5) lib/rack/conditionalget.rb:25:in`call'
actionpack (3.2.16) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.16) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
actionpack (3.2.16) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.5) lib/rack/session/abstract/id.rb:210:in`context'
rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.16) lib/action_dispatch/middleware/cookies.rb:341:in`call'
activerecord (3.2.16) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.16) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in`call'
actionpack (3.2.16) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.16) lib/active_support/callbacks.rb:405:in`_run__4533570937447988270__call__1367243920795582187__callbacks'
activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.16) lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
activesupport (3.2.16) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.16) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
actionpack (3.2.16) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.16) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
actionpack (3.2.16) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.16) lib/rails/rack/logger.rb:32:in`call_app'
railties (3.2.16) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.16) lib/active_support/tagged_logging.rb:22:in`tagged'
railties (3.2.16) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.16) lib/action_dispatch/middleware/request_id.rb:22:in`call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.5) lib/rack/runtime.rb:17:in`call'
activesupport (3.2.16) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.5) lib/rack/lock.rb:15:in`call'
actionpack (3.2.16) lib/action_dispatch/middleware/static.rb:63:in `call'
rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
railties (3.2.16) lib/rails/engine.rb:484:in `call'
railties (3.2.16) lib/rails/application.rb:231:in`call'
railties (3.2.16) lib/rails/railtie/configurable.rb:30:in `method_missing'
passenger (4.0.37) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in`process_request'
passenger (4.0.37) lib/phusion_passenger/request_handler/thread_handler.rb:142:in `accept_and_process_next_request'
passenger (4.0.37) lib/phusion_passenger/request_handler/thread_handler.rb:110:in`main_loop'
passenger (4.0.37) lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

What is the problem?

System: Linux version 2.6.32-431.5.1.el6.x86_64 (mockbuild@c6b10.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) )
Http server: Apache/2.2.15 (Unix)

Regards
Mariusz

**Comment by eXtreemru** [comment]
Having the same Issue here:
Started GET "/rb/releases_multiview/1" for XXXXXXXX at XXXXXXXXX 10:32:11 +0100
Processing by RbReleasesMultiviewController#show as HTML
  Parameters: {"release_multiview_id"=>"1"}
  Current user: s.kovalev (id=5)
  Rendered plugins/redmine_backlogs/app/views/rb_releases_multiview/show.html.erb within layouts/base (135.7ms)
Completed 500 Internal Server Error in 150.0ms

ActionView::Template::Error (NaN):
    36: <% unless @release_multiview.has_burnchart? %>
    37:   <%= render :partial => 'releases', :locals => { :releases => @release_multiview.releases } %>
    38: <% else %>
    39:   <%= render :partial => 'releases_estimate', :locals => { :releases => @release_multiview.burnchart.releases_estimate } %>
    40: <% end %>
    41: 
    42: 
  activesupport (3.2.21) lib/active_support/core_ext/date/calculations.rb:90:in `floor'
  activesupport (3.2.21) lib/active_support/core_ext/date/calculations.rb:90:in `+'
  activesupport (3.2.21) lib/active_support/core_ext/date/calculations.rb:90:in `plus_with_duration'
  plugins/redmine_backlogs/lib/linear_regression.rb:38:in `crossing_date'
  plugins/redmine_backlogs/app/models/rb_stacked_data.rb:89:in `block in calculate_estimate_end_days'
  plugins/redmine_backlogs/app/models/rb_stacked_data.rb:88:in `each'
  plugins/redmine_backlogs/app/models/rb_stacked_data.rb:88:in `calculate_estimate_end_days'
  plugins/redmine_backlogs/app/models/rb_stacked_data.rb:60:in `finalize'
  plugins/redmine_backlogs/app/models/rb_release_multiview_burnchart.rb:28:in `initialize'
  plugins/redmine_backlogs/app/models/rb_release_multiview.rb:26:in `new'
  plugins/redmine_backlogs/app/models/rb_release_multiview.rb:26:in `burnchart'
  plugins/redmine_backlogs/app/views/rb_releases_multiview/show.html.erb:39:in `_plugins_redmine_backlogs_app_views_rb_releases_multiview_show_html_erb__3300773448280412909_70226844156260'
  actionpack (3.2.21) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.21) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.21) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
  actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:18:in `render'
  actionpack (3.2.21) lib/action_view/renderer/renderer.rb:36:in `render_template'
  actionpack (3.2.21) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:110:in `_render_template'
  actionpack (3.2.21) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:103:in `render_to_body'
  actionpack (3.2.21) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.21) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /usr/local/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `ms'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:39:in `render'
  plugins/redmine_backlogs/app/controllers/rb_releases_multiview_controller.rb:13:in `block (2 levels) in show'
  actionpack (3.2.21) lib/action_controller/metal/mime_responds.rb:196:in `call'
  actionpack (3.2.21) lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
  plugins/redmine_backlogs/app/controllers/rb_releases_multiview_controller.rb:12:in `show'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.21) lib/active_support/callbacks.rb:513:in `_run__4078709836635228388__process_action__435676215067110402__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__2350550712766702522__call__1817282779616575213__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in `call'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (4.0.57) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  passenger (4.0.57) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.57) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.57) lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

Using Backlogs v1.0.6 on Redmine 2.6.1.stable.13882 under Debian Weezy
