### ISSUE TITLE
installation fails: ArgumentError: Unknown key: :order.

### ISSUE THREAD

**Issue by magwas** [backlogs/redmine_backlogs#1098]
$ruby -v

    ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-linux]

$head -8 ./lib/redmine/version.rb

    require 'rexml/document'

    module Redmine
      module VERSION #:nodoc:
        MAJOR = 2
        MINOR = 6
        TINY  = 0

$RAILS_ENV=production bundle exec rake db:migrate
rake aborted!
ArgumentError: Unknown key: :order. Valid keys are: :class_name, :class, :foreign_key, :validate, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/hash/keys.rb:71:in `block in assert_valid_keys'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/hash/keys.rb:69:in `each_key'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/hash/keys.rb:69:in `assert_valid_keys'
/usr/local/rvm/gems/ruby-2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/builder/association.rb:81:in `validate_options'
/usr/local/rvm/gems/ruby-2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/builder/association.rb:61:in `initialize'
/usr/local/rvm/gems/ruby-2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/builder/collection_association.rb:18:in `initialize'
/usr/local/rvm/gems/ruby-2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/builder/association.rb:46:in `new'
/usr/local/rvm/gems/ruby-2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/builder/association.rb:46:in `create_builder'
/usr/local/rvm/gems/ruby-2.1.0/gems/activerecord-4.1.8/lib/active_record/associations/builder/association.rb:35:in `build'
/usr/local/rvm/gems/ruby-2.1.0/gems/activerecord-4.1.8/lib/active_record/associations.rb:1215:in `has_many'
/var/www/redmine/plugins/redmine_backlogs/lib/backlogs_project_patch.rb:176:in `block in included'
/var/www/redmine/plugins/redmine_backlogs/lib/backlogs_project_patch.rb:174:in `class_eval'
/var/www/redmine/plugins/redmine_backlogs/lib/backlogs_project_patch.rb:174:in `included'
/var/www/redmine/plugins/redmine_backlogs/lib/backlogs_project_patch.rb:346:in `include'
/var/www/redmine/plugins/redmine_backlogs/lib/backlogs_project_patch.rb:346:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:348:in `require_or_load'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:307:in `depend_on'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:225:in `require_dependency'
/var/www/redmine/plugins/redmine_backlogs/init.rb:32:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:438:in `instance_exec'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:438:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:184:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:184:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:185:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:185:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.1.8/lib/rails/application/finisher.rb:52:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.1.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.1.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.1.8/lib/rails/application.rb:300:in `initialize!'
/var/www/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.1.8/lib/rails/application.rb:276:in `require_environment!'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.1.8/lib/rails/application.rb:389:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

**Comment by korin** [comment]
maybe too new active record/other gems?
try add `gem 'activerecord-deprecated_finders', require: 'active_record/deprecated_finders'` to `Gemfile.local` and bundle install and restart server

**Comment by m-behr** [comment]
@korin fixed it, thank you. 
cosmetic: 'Gemfile.local' is called 'Gemfile'  on my system.
