### ISSUE TITLE
Redmine 3.2.0 installation issue

### ISSUE THREAD

**Issue by s0l4r** [backlogs/redmine_backlogs#1114]
Hi,

Is backlogs compatible with Redmine 3.2.0? I have issues installing it. If not, which version of Redmine and Ruby/Rails do you recommend to use, is 3.x compatible at all or should we use 2.6 still?

      Redmine version                3.2.0.stable
      Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]
      Rails version                  4.2.5
      Environment                    production
      Database adapter               Mysql2
    SCM:
      Subversion                     1.6.17
      Cvs                            1.12.12
      Git                            1.7.12.4
      Filesystem                     

    /opt/redmine/.rvm/gems/ruby-2.2.1/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot" [0/9398]
    /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/scoping/named.rb:143:in `scope': The scope body needs to be callable. (ArgumentError)
    from /opt/redmine/redmine-3.2.0/plugins/redmine_backlogs/app/models/rb_release.rb:174:in `<class:RbRelease>'
    from /opt/redmine/redmine-3.2.0/plugins/redmine_backlogs/app/models/rb_release.rb:156:in `<top (required)>'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:360:in `require_or_load'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:494:in `load_missing_constant'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:526:in `load_missing_constant'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:526:in `load_missing_constant'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
    from /opt/redmine/redmine-3.2.0/plugins/redmine_backlogs/lib/backlogs_issue_query_patch.rb:31:in `block in included'
    from /opt/redmine/redmine-3.2.0/plugins/redmine_backlogs/lib/backlogs_issue_query_patch.rb:25:in `class_eval'
    from /opt/redmine/redmine-3.2.0/plugins/redmine_backlogs/lib/backlogs_issue_query_patch.rb:25:in `included'
    from /opt/redmine/redmine-3.2.0/plugins/redmine_backlogs/lib/backlogs_issue_query_patch.rb:145:in `include'
    from /opt/redmine/redmine-3.2.0/plugins/redmine_backlogs/lib/backlogs_issue_query_patch.rb:145:in `<top (required)>'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:360:in `require_or_load'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:317:in `depend_on'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:233:in `require_dependency'
    from /opt/redmine/redmine-3.2.0/plugins/redmine_backlogs/init.rb:27:in `block in <top (required)>'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:446:in `instance_exec'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:446:in `block in make_lambda'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:192:in `call'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:192:in `block in simple'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `block in call'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `each'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.5/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /opt/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
    from /opt/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from /opt/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
    from /opt/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from /opt/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
    from /opt/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
    from /opt/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
    from /opt/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
    from /opt/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
    from /opt/redmine/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
    from /opt/redmine/redmine-3.2.0/config/environment.rb:14:in `<top (required)>'
    from /opt/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /opt/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from bin/about:4:in `<main>'

gem list

*** LOCAL GEMS ***

actionmailer (4.2.5)
actionpack (4.2.5)
actionpack-action_caching (1.1.1)
actionpack-xml_parser (1.0.2)
actionview (4.2.5)
activejob (4.2.5)
activemodel (4.2.5)
activerecord (4.2.5)
activesupport (4.2.5)
addressable (2.4.0)
arel (6.0.3)
bigdecimal (1.2.7, 1.2.6)
builder (3.2.2)
bundler (1.11.1)
bundler-unload (1.0.2)
coderay (1.1.0)
concurrent-ruby (1.0.0)
css_parser (1.3.7)
daemons (1.2.3)
erubis (2.7.0)
eventmachine (1.0.8)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
globalid (0.3.6)
holidays (3.0.0, 1.0.8, 1.0.3)
htmlentities (4.3.4, 4.3.1)
i18n (0.7.0)
icalendar (2.3.0)
io-console (0.4.3)
jquery-rails (4.0.5, 3.1.4)
json (1.8.3, 1.8.1)
loofah (2.0.3)
mail (2.6.3)
mime-types (3.0, 2.99)
mime-types-data (3.2015.1120)
mini_portile (0.5.3)
mini_portile2 (2.0.0)
minitest (5.8.3, 5.4.3)
mysql2 (0.4.2, 0.3.20)
net-ldap (0.12.1)
nokogiri (1.6.0)
open-uri-cached (0.0.5)
passenger (5.0.22)
pdf-core (0.6.0)
power_assert (0.2.6, 0.2.2)
prawn (2.0.2)
protected_attributes (1.1.3)
psych (2.0.16, 2.0.8)
rack (1.6.4)
rack-openid (1.4.2)
rack-test (0.6.3)
rails (4.2.5)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.2)
railties (4.2.5)
rake (10.4.2)
rbpdf (1.19.0)
rbpdf-font (1.19.0)
rdoc (4.2.0)
redcarpet (3.3.3)
request_store (1.2.1, 1.0.5)
rmagick (2.15.4)
roadie (3.1.1)
roadie-rails (1.1.0)
ruby-openid (2.7.0, 2.3.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
sprockets (3.5.2)
sprockets-rails (2.3.3)
test-unit (3.1.5, 3.0.8)
thin (1.6.4)
thor (0.19.1)
thread_safe (0.3.5)
ttfunk (1.4.0)
tzinfo (1.2.2)
yard (0.8.7.6)

**Comment by s0l4r** [comment]
Update:
redmine_backlogs seems to be working with git branch feature/redmine3 and Redmine 3.2.0.

The only thing needed was to correct the conflicting version of nokogiri in the Gemfile.

**Comment by liyamahendra** [comment]
@s0l4r I'm able to install backlogs but when I click on the "backlogs" tab, it results into 500 Internal Server error. what exactly did you change the version to for nokogiri? Thanks!

**Comment by kirantpatil** [comment]
@liyamahendra , I removed the nokigiri entry from plugin Gemfile and it did migration and it worked.

**Comment by RaviSambaraju** [comment]
(kirantpatil ),I removed the nokogiri but am not able to installing...
please can you provide your backlogs plugin gem list..

**Comment by kirantpatil** [comment]
Sorry I dont have backup. I found it is not much intuitive so moved to wekan.io.

**Comment by RaviSambaraju** [comment]
ok Thank you for responding sharply..
