### ISSUE TITLE
backlogs_activerecord_mixin.rb causes an error

### ISSUE THREAD

**Issue by Shin811** [backlogs/redmine_backlogs#1144]
Hi,

When you change the ticket, the following error occurs.

>ActiveRecord::StatementInvalid (Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where id = 566' at line 1: update issues set position =  where id = 566):
>  plugins/redmine_backlogs/lib/backlogs_activerecord_mixin.rb:170:in `list_commit'
>  plugins/redmine_backlogs/lib/backlogs_activerecord_mixin.rb:83:in `move_to_top'
>  plugins/redmine_backlogs/lib/backlogs_issue_patch.rb:134:in `backlogs_before_save'
>  app/models/issue.rb:182:in `create_or_update'
>  app/controllers/issues_controller.rb:487:in `block in save_issue_with_child_records'
>  app/controllers/issues_controller.rb:475:in `save_issue_with_child_records'
>  app/controllers/issues_controller.rb:180:in `update'
>  lib/redmine/sudo_mode.rb:63:in `sudo_mode'`

Commenting out list_commit in the 83 line of backlogs_activerecord_mixin.rb  to try it worked normally.
Can you tell me what is going on?
My environment is as follows.

Best regards

>Environment:
>  Redmine version                3.2.1.stable
>  Ruby version                   2.1.8-p440 (2015-12-16) [i386-mingw32]
>  Rails version                  4.2.5.2
>  Environment                    production
>  Database adapter               Mysql2
>SCM:
>  Subversion                     1.8.11
>  Git                            2.7.4
>  Filesystem                     
>Redmine plugins:
>  alm                            1.0.5
>  clipboard_image_paste          1.10
>  lad                            1.4.1
>  lgc                            3.2.0
>  lgc_pro                        3.2.0
>  redmine_agile                  1.4.2
>  redmine_backlogs               v1.0.6
>  redmine_banner                 0.1.2
>  redmine_checklists             3.1.5
>  redmine_issue_completion       0.0.2
>  redmine_issue_templates        0.1.4
>  redmine_wiki_extensions        0.7.0
>  redmine_work_days              1.1.0
>  redmine_work_time              0.3.4
>  sidebar_hide                   0.0.8'

**Comment by wmlynar** [comment]
would you mind checking if that is a conflict with redmine_agile plugin by temporary moving it to other directory and trying again?

**Comment by rabbl** [comment]
I had the same error. 
Unistallung the redmine_agile plugin helped.

**Comment by mtolava** [comment]
I had the same error.
I need to use redmine_agile plugin. There are no alternative to fix this problem?

**Comment by humming-soft** [comment]
> I had the same error. I need to use redmine_agile plugin. There are no alternative to fix this problem?

Have you resolved?

**Comment by sebint** [comment]
> I had the same error. I need to use redmine_agile plugin. There are no alternative to fix this problem?

Have you resolved your issue?
