### ISSUE TITLE
got 500 error when i click 'issues' menu

### ISSUE THREAD

**Issue by namjae** [backlogs/redmine_backlogs#1148]
hi, i'm using @TheMagician1 's fork with redmine 3.4.2.stable.

got following error when i click 'issues' menu
```
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back
```

**log/production.log:**
```
Started GET "/projects/infra/issues" for 192.168.0.7 at 2017-08-21 03:13:47 +0900
Processing by IssuesController#index as HTML
  Parameters: {"project_id"=>"infra"}
  Current user: dhpark (id=6)
  Rendered queries/_filters.html.erb (11.6ms)
  Rendered queries/_query_form.html.erb (12.2ms)
  Rendered issues/index.html.erb within layouts/base (14.3ms)
Completed 500 Internal Server Error in 62ms (ActiveRecord: 15.2ms)

ActionView::Template::Error (undefined method `remote' for #<Hash:0x007f859e2c5300>):
    1: <%= javascript_tag do %>
    2: var operatorLabels = <%= raw_json Query.operators_labels %>;
    3: var operatorByType = <%= raw_json Query.operators_by_filter_type %>;
    4: var availableFilters = <%= raw_json query.available_filters_as_json %>;
    5: var labelDayPlural = <%= raw_json l(:label_day_plural) %>;
    6: 
    7: var filtersUrl = <%= raw_json queries_filter_path(:project_id => @query.project.try(:id), :type => @query.type) %>;
  app/models/query.rb:464:in `block in available_filters_as_json'
  app/models/query.rb:462:in `each'
  app/models/query.rb:462:in `available_filters_as_json'
  app/views/queries/_filters.html.erb:4:in `block in _app_views_queries__filters_html_erb__558628764505366421_70105938951260'
  app/views/queries/_filters.html.erb:1:in `_app_views_queries__filters_html_erb__558628764505366421_70105938951260'
  app/views/queries/_query_form.html.erb:10:in `_app_views_queries__query_form_html_erb___1723964526481353628_70105939162080'
  app/views/issues/index.html.erb:11:in `block in _app_views_issues_index_html_erb__571009017425664742_70105939521140'
  app/views/issues/index.html.erb:10:in `_app_views_issues_index_html_erb__571009017425664742_70105939521140'
  app/controllers/issues_controller.rb:51:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:46:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**my environment:**
```
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_backlogs               v2.0.2
```

**Comment by surick1** [comment]
Here is [workaround](http://www.redmine.org/issues/26637).
