### ISSUE TITLE
An error occurred while installing json

### ISSUE THREAD

**Issue by Glideh** [backlogs/redmine_backlogs#737]
I'm trying to install redmine_backlogs but getting an error

``` shell
$ pwd
/usr/share/redmine/vendor/plugins/redmine_backlogs
$ sudo bundle install
Updating https://github.com/Vanuan/cucumber-rails.git
Fetching gem metadata from http://rubygems.org/.......
Fetching gem metadata from http://rubygems.org/..
Using Ascii85 (1.0.2) 
Using hashery (2.0.1) 
Using holidays (1.0.3) 
Using icalendar (1.2.0) 
Installing json (1.7.5) with native extensions 
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb 
/usr/local/lib/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/local/lib/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from extconf.rb:1:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-1.7.5 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/json-1.7.5/ext/json/ext/generator/gem_make.out
An error occurred while installing json (1.7.5), and Bundler cannot continue.
Make sure that `gem install json -v '1.7.5'` succeeds before bundling.
```

I don't know much about Ruby.
What am I doing wrong ?

(I'm using Ubuntu)

**Comment by scipper** [comment]
@Glideh this perfectly did it!
